directories:
  output: dist-electron
  buildResources: build
appId: com.hospital.kiosk
productName: 醫院掛號系統
asar: false
files:
  - filter:
      - dist/**/*
      - electron.cjs
      - preload.cjs
      - package.json
      - server/**/*
      - node_modules/**/*
win:
  target: portable
  icon: public/icon.png
electronVersion: 33.4.11
